### ISSUE TITLE
스마트 컨트랙트 ToDo 리스트

### ISSUE THREAD

**Issue by 0x-Robert** [codestates-beb/BEB-08-second-TokenInside#10]
# 스마트 컨트랙트 To Do 리스트

### 1. ERC-20 컨트랙트 

- [x] ERC-20 컨트랙트 한글주석화
- [x] ERC-20 컨트랙트 고얼리 테스트넷 배포 
    - [x] 백엔드와 연동 - 최소요구사항 만족
<hr/>

### 2. ERC-721 컨트랙트 

- [x] ERC-721 컨트랙트 한글주석화
    - [x] ERC-721 컨트랙트 고얼리 테스트넷 배포 
    - [x] 백엔드와 연동 - 최소요구사항 만족

    
<hr/>
